### ISSUE TITLE
"Not a valid parameter" error

### ISSUE THREAD

**Issue by nkniep888** [grantbrown/ABSEIR#11]
Hi again,
Thanks for your previous responses and help! We are running into an error when trying to run our model (copied below) and can't quite figure out what the source is. Could you provide some ideas of where this error might be stemming from? Thank you!
   
Initializing Model Components
    ...Building data model
    ...Building distance model
    ...Building exposure model
    ...Building initial value container
    ...Building reinfection model
    ...Building sampling control model
    ...Building transition priors
    ...Preparing model object
    Running main simulation
    Iteration 0 [8869.03, 8869.03]  eps: 8870.03
    Starting from parameter with zero probability.
      Param:
        2.74275   -0.773173    -2.24658     1.74023     -2.2299    0.028799    0.555275    0.399456         nan    0.498545      194004      200795      164269       79201 1.02813e+06      127665      217172       29438       87797      255863        1489        1570        1257         590        7705         995        1662         227         672        1931          32          21          21           3         336          17          38           2          13          36          30          21          21           3         335          16          38           2          13          36
    Errors generated:

    <Rcpp::exception in modelComponents[["SEIR_model"]]$sample(samples, sampling_control$keep_compartments *     1, verbose * 1): Not a valid parameter.>

**Comment by grantbrown** [comment]
Hmm, I'll need a little bit more info, but that "nan" is likely the issue. When you get a chance, try:

1. Set verbose to 2, and copy all the output you see. 
2. Double check that you're using the latest version on the master branch from Github. If it's been a while since you installed the package, you'll want to reinstall the latest version.

**Comment by nkniep888** [comment]
Okay, we reinstalled the package and set verbose to 2. Error output below:

    Initializing Model Components
    ...Building data model
    ...Building distance model
    ...Building exposure model
    ...Building initial value container
    ...Building reinfection model
    ...Building sampling control model
    ...Building transition priors
    ...Preparing model object
    Running main simulation
    Starting sampler
    Number of iterations requested: 100
    Data Model Summary
    ------------------
        Number of locations: 10
        Number of time points: 126
        Data Model Compartment: I_star
        Data Model Type: identity
    Exposure Model Summary
    ----------------------    dim(X): (1260, 5)
        beta prior means: (0,
                           0,
                           0,
                           0,
                           0)
        beta prior precision: (0.5,
                               0.5,
                               0.5,
                               0.5,
                               0.5)
    Transition Priors Summary
    -------------------------
        transition mode: exponential
        E to I transition prior params: (143255, nan)
         I to R transition prior params: (9, 25.4756)
     Reinfection Model Summary
    -------------------------
        reinfection mode: SEIR
    Distance Model Summary
    ----------------------
    Number of locations: 10
    Number of distance structures: 3
    Number of time varying distance structures: 126
    Number of time varying distance lags: 0
    Initial Compartment Values - Summary
    ------------------------------------
        S0, E0, I0, R0
        194004, 1489, 32, 30
        200795, 1570, 21, 21
        164269, 1257, 21, 21
        79201, 590, 3, 3
        1028133, 7705, 336, 335
        127665, 995, 17, 16
        217172, 1662, 38, 38
        29438, 227, 2, 2
        87797, 672, 13, 13
        255863, 1931, 36, 36
    Sampling Control Summary
    ------------------------
        algorithm: 2
        simulation_width: 1
        random_seed: 123123
        CPU_cores: 14
        init_batch_size: 5000
        batch_size: 5000
        epochs: 100
        max_batches: 20
        multivariatePerturbation: 0
        m: 1
        accept_fraction: -1
        shrinkage: 0.9
        lpow: 2
        target_eps: 0
        Note: not all parameters are used for all algorithms.
    Generating starting parameters from prior
    Error, valid rho value not obtained
    Error, valid rho value not obtained
    Iteration 0 [8869.03, 8869.03]  eps: 8870.03
    Starting from parameter with zero probability.
      Param:
       -1.23545     1.65744    -3.56405     1.21543    -1.42619    0.130692    0.354539    0.444715         nan    0.413872      194004      200795      164269       79201 1.02813e+06      127665      217172       29438       87797      255863        1489        1570        1257         590        7705         995        1662         227         672        1931          32          21          21           3         336          17          38           2          13          36          30          21          21           3         335          16          38           2          13          36
    Errors generated:
    <Rcpp::exception in modelComponents[["SEIR_model"]]$sample(samples, sampling_control$keep_compartments *     1, verbose * 1): Not a valid parameter.>
    Error in value[[3L]](cond) : Aborting

**Comment by grantbrown** [comment]
There may be other issues as well, but there's certainly something wrong with your transition priors - can you post the code where that's specified?

    E to I transition prior params: (143255, nan)

**Comment by nkniep888** [comment]
Sure. 

`# transition model
  # create transition model parameters:
  ProbExposedtoInfected <- (runif(1, min = 92, max = 100)) # random value between 92 and 100
  ProbInfectedtoRecovered <- CFR # Meck CFR (# deaths/# cases * 100) for the date range
  SmpleSizeExposedtoInfected <- CountyStats$E0 * 
    ProbExposedtoInfected # multiply sample size by probability (E0 * pEi)
  SmpleSizeInfectedToRecovered <- CountyStats$I0 * 
    ProbInfectedtoRecovered # multiply sample size by probability (I0 * pIr)
  
  # create transition model: 
  transition_priors = ExponentialTransitionPriors(p_ei = ProbExposedtoInfected,
                                p_ir = ProbInfectedtoRecovered,
                                p_ei_ess = SmpleSizeExposedtoInfected,
                                p_ir_ess = SmpleSizeInfectedToRecovered)`

**Comment by grantbrown** [comment]
What numeric values do the arguments to ExponentialTransitionPriors actually take on?

**Comment by nkniep888** [comment]
transition_priors = ExponentialTransitionPriors(p_ei = 93.22825,
                                p_ir = 0.297619,
                                p_ei_ess = 138816.87 146368.36 117187.91  55004.67 718323.70  92762.11 154945.36  21162.81  62649.39 180023.76,
                                p_ir_ess = 9.5238095   6.2500000   6.2500000   0.8928571  100.0000000   5.0595238  11.3095238   0.5952381   3.8690476  10.7142857)

**Comment by grantbrown** [comment]
There's your issue: p_ei = 93.22825

This is supposed to be a probability, so it needs to be between zero and one. I'll look at adding validation to those fields - we should be catching that earlier and giving the user a better error message.

**Comment by nkniep888** [comment]
Okay. I updated the p_ei value to be 0.93. I'm still getting the same error output though, mainly "Error, valid rho value not obtained" repeating many times. Unsure if that issue stems from the data, exposure, or distance models.

**Comment by grantbrown** [comment]
That's coming from the distance model, or rather, it's arising when spatial auto-correlation terms are sampled from the prior. These models assume that most infection should be happening within a spatial unit rather than between them, so there's a soft constraint on the auto-correlation terms to sum to less than one. This is a pretty squishy constraint, given that we're not actually constraining the scale of the distance matrices, but the error is there to warn the user that the parameters chosen may be unstable/ inconsistent. It doesn't actually stop the sampler, but if it happens a lot then it will spam that message (probably not ideal). It should probably be called a "warning" for that reason. 

This is likely happening since you have a number of distance structures, but may not have changed the prior parameters for the auto-correlation terms. If you change the prior alpha and beta (for a gamma distribution) to give a lower mean, that should help keep your sampler in a reasonable region of the parameter space. For example, try setting alpha = 1, beta = 10.

**Comment by nkniep888** [comment]
I see, thank you!
