### ISSUE TITLE
Time-varying distance matrix? 

### ISSUE THREAD

**Issue by caseyzipfel** [grantbrown/ABSEIR#13]
Hi! Thanks for the package! 
I was wondering if it was possible to incorporate changes in the distance matrix over time. For example, if I was modeling the COVID-19 pandemic, and I had some weekly data on the movement between states, and how it decreases in the pandemic due to travel restrictions. Could I parameterize the distance matrix to account for this reduction in movement? Thank you!

**Comment by grantbrown** [comment]
Hi Casey, yep, that's possible to do with the TDistanceModel constructor. It should be better documented, but there's a dummy example of how that could work given in the [tests](https://github.com/grantbrown/ABSEIR/blob/master/tests/testthat/testTDistanceModels.R). It is possible to implement both simple time varying distance matrices, as well as lagged distance effects.
