### ISSUE TITLE
Clarification of model specification

### ISSUE THREAD

**Issue by caseyzipfel** [grantbrown/ABSEIR#14]
Hi! Thanks for the very useful package. 
I have been looking into the model specification, to understand how each of the model components are incorporated. Something that is unclear to me from the paper "Approximate Bayesian computation for spatial SEIR(S) epidemic models" is how the number of infected individuals at the previous timestep impact the exposure probability (pi_SE in the paper). Perhaps I am just overlooking this. Could you point me to where I could find this in the model equations, or provide additional explanation of how this is incorporated? Thank you!

**Comment by grantbrown** [comment]
Hi Casey, 

The short answer is that there's an I/N term, the infectious fraction, that enters the pi_SE term at the following time point. The form of the probability is based on assuming that the distribution of contacts for each individual at a given time point is Poisson with some intensity, and that conditional on a contact between a susceptible person and an infectious person there is some probability of infection. These processes aren't usually jointly identifiable, so their product is what we call "intensity", and that's what the form of the `ExposureModel` in ABSEIR controls. 

A more basic version of this form is given in Lekone and Finkenstadt 2006:

![PSE](https://user-images.githubusercontent.com/1713575/98834168-8123ac80-2404-11eb-8df2-20d3f6492e85.png)

![pSE_intensity](https://user-images.githubusercontent.com/1713575/98834188-87198d80-2404-11eb-8ef6-476de192400f.png)

This form uses just a baseline intensity (which we treat as an intercept), and an intervention term (which is analogous to to the one we use in [this vignette](https://grantbrown.github.io/ABSEIR/vignettes/Kikwit.html))

The full spatial version we use additionally splits the contact process up over space (and potentially lagged over time). 

Let me know if you have any follow-up thoughts or questions.

**Comment by caseyzipfel** [comment]
Hi Grant! Thank you for your quick and helpful response! 
Another question that I had as I worked with this package: 
On what scale are the model outputs of gamma_E_I and gamma_I_R? I have been unsure about my interpretation of the model estimated gamma_E_I and gamma_I_R, and how the transition prior relate. 
Here is my guess thus far based on the MeaslesWeserEms example, please let me know if I am misunderstanding any of it!
In the MeaslesWeserEms example, it looks like the transition priors should be the probability of transition between compartments per week, from the lines
(p_ei = 0.8, # Guess at E to I transition probability (per week)
p_ir = 0.8, # Guess at I to R transition probability (per week))
My understanding is that this would indicate a latent and infectious period of about 5.6 days, since:
1/gamma = weekly transition rate = period in days * (1 week / 7days) 
Weekly transition rate = 5.6 days * (1 week/ 7 days) = 0.8 
So gamma should be about 1.25, since 1/1.25 = 0.8
And, the MeaslesWeserEms model estimates in the vignette are between 1.2 - 1.6, so the model outputs the gamma, rather than a transition probability. 
Is what I have worked out correct? Thank you in advance!

**Comment by grantbrown** [comment]
Hi Casey, that's mostly correct. When using the ExponentialTransitionPriors, the transition probabilities are of the form:

p = 1-exp(-gamma)

So if p_ei = 0.8 then gamma_ei = 1.61. The model does output the gamma estimates in this case, but you can compute the transition probabilities directly. 

There's a little bit of subtlety with the discrete time support which is worth noting though. While these models are related to continuous time formulations which assume an exponential compartment membership time, the discrete nature of the models turn that into a geometric compartment membership time distribution. That means it may not be meaningful to think about transition rates at a granularity below that which is used in the model (if we're using weekly data, transitions which happen in less than one week can't occur - everyone gets forced to stay in the state for at least one week). That may or may not matter for particular problems, and we can generally go to a finer granularity if it does (even if we have only weekly data, we could treat it on a cumulative scale and record daily observations at the end of each week). 

Working at an increased granularity does, of course, come with computational costs. Also, if this sort of thing is important to the dynamics of a particular pathogen, then the exponential/geometric assumption is probably not reasonable anyway, and it would be better to use something like the Weibull path-specific transition structure. 

Hope that helps, 
-Grant
