### ISSUE TITLE
Plotting R0 number in tutorial

### ISSUE THREAD

**Issue by simonbrewer** [grantbrown/ABSEIR#15]
I am currently working through the first tutorial, and get the following error when trying to plot the R0 number:

`Error in apply(allSimulatedR0, 1, mean) : 
  dim(X) must have a positive length`

I think the `plotR0` function is trying to get the R0 number from `simulations1$simulationResults` (where `simulations1` is the output from `epidemic.simulations`, but this doesn't appear to contain `R0`. E.g. `simulations1$simulationResults$Simulation_1$R0` returns `NULL`

I believe I copied the code correctly, but have probably missed something. Is there a parameter I need to set to estimate this number in each simulation? 

Thanks! And thanks for the great package - the tutorial is really useful

**Comment by grantbrown** [comment]
Hi Simon, it's not you, I really need to update that vignette (and also to re-do R0 calculations entirely). 

Currently, the traditional R0(t) isn't calculated at all in through the computeR0, and you'd be better off calculating it by hand from the estimated parameters. Here's an example which should work, showing the calculation of the traditional R0(t) measure and an empirical version:



```
plotR0 = function(simulations, main)
{
  allSimulatedR0t <- sapply(simulations$simulationResults, function(x){
    # Traditional estimate of R0(t)
    exp(x$X %*% t(x$beta))/(-log(1-x$p_ir[1]))
  })
  allSimulatedE_R0 = sapply(simulations$simulationResults, function(x){
    # (New infectious per infectious person at a given time point)*(average infectious duration)
    E_R0 <- (x$E_star/x$I)/t(x$p_ir)
    E_R0 <- ifelse(is.na(E_R0) | E_R0 == 0, 0, E_R0)
    # Smoothed
    ksmooth(x=1:length(E_R0),y=E_R0, kernel = "normal", bandwidth = 20)$y
  })

  plot(apply(allSimulatedR0t, 1, median), type = "l", ylim = c(0, 5), lwd =2,
       ylab = "Reproductive Number", main = main)
  lines(apply(allSimulatedR0t, 1, mean), lwd = 2, lty = 2, col = "blue")
  lines(apply(allSimulatedR0t, 1, quantile, probs = c(0.1)), lwd = 2, lty = 2, col = "blue")
  lines(apply(allSimulatedR0t, 1,  quantile, probs = c(0.9)), lwd = 2, lty = 2, col = "blue")
  
  lines(apply(allSimulatedE_R0, 1, median,na.rm=TRUE), col = "red", lwd =2, lty = 1)
  lines(apply(allSimulatedE_R0, 1, quantile, probs = c(0.1)), col = "red", lwd =2, lty = 2)
  lines(apply(allSimulatedE_R0, 1, quantile, probs = c(0.9)), col = "red", lwd =2, lty = 2)
  
  
}
plotR0(simulations1, "Two Measures of R0")
plotR0(simulations2, "Two Measures of R0")
```

**Comment by simonbrewer** [comment]
This works great! (Although I clearly need to read your text on the different R0 measures). Thanks for the quick reply.
