### ISSUE TITLE
R0t and R_EA returning NULL

### ISSUE THREAD

**Issue by Arminn-Potgieter** [grantbrown/ABSEIR#19]
Hello there

Once again thank you very much for your assistance on my previous issue. I am currently encountering an issue where the R0t and R_EA functions are both returning only NULL values. I have included a reproducible example based on the "Kikwit Ebola Aanalysis" tutorial (with only some unnecessary code removed) showcasing this issue. Any assistance regarding this issue would be greatly appreciated.
[R0 Issue.zip](https://github.com/grantbrown/ABSEIR/files/7135886/R0.Issue.zip)

**Comment by grantbrown** [comment]
Hmm, I'll take a look and see what's going on.

**Comment by grantbrown** [comment]
There were a couple issues:

1. A while back I switched to doing the R0 computation in a separate function to save time when it isn't required (it's implemented in R)
2. There were some issues with that function related to recent changes. 

I need to update the vignettes still, but [this gist](https://gist.github.com/grantbrown/9c9e08e4d2d4aea37b928efe2d27d764) shows the code for getting the EA-RN curves and how to calculate R0. You'll want to make sure to get the latest changes and reinstall the package.
