### ISSUE TITLE
ABSEIR for Dengue

### ISSUE THREAD

**Issue by Spatial-R** [grantbrown/ABSEIR#2]
My problem is how to use the ABSEIR model to model the dynamic of Dengue? Dengue is a mosquito-borne viral diseases in the world, therefore, a dynamic model including the transmission both the population compartment and vector compartment is essential [Reference Paper](http://download.springer.com/static/pdf/815/art%253A10.1186%252F2049-9957-3-12.pdf?originUrl=http%3A%2F%2Fidpjournal.biomedcentral.com%2Farticle%2F10.1186%2F2049-9957-3-12&token2=exp=1476282319~acl=%2Fstatic%2Fpdf%2F815%2Fart%25253A10.1186%25252F2049-9957-3-12.pdf*~hmac=47ed9e78e1a77f1446e5bbbaf08258a327d4735bd587f55fcf56fe8aaf8ff2a4). 

Is there any solution to do this?

**Comment by grantbrown** [comment]
Currently, ABSEIR is designed to model host to host transmission, but as an imperfect workaround you could first use other software to model the transmission pressure of the vector, and use it as a spatiotemporal covariate in the exposure process. 

One of the features I'm currently working on is a lagged contact structure, which will be able to handle the kind of delayed transmission introduced by a vector, but it's not yet complete. 

Edit: you can always treat different species like different locations, and structure the contact matrices appropriately. This may, or may not, make sense, depending on the transmission dynamics.

**Comment by Spatial-R** [comment]
As you know, vector transmission strongly depends on the infection population. Therefore, i wait for your lagged contact structure model. If you have finished the project, please let me know. Thanks.

**Comment by grantbrown** [comment]
The lagged contact model is  now implemented, but I haven't yet used it in any production models. If you want a peak into how it works, check out the "tests" folder of the package. 

Hope that helps,
