### ISSUE TITLE
Different definations to the spatial matrix

### ISSUE THREAD

**Issue by Spatial-R** [grantbrown/ABSEIR#4]
Hello, I'm sorry to bother you again for the issue i came across when used the ABSEIR to analysis my dataset. I have followed the step in the ducument of [http://grantbrown.github.io/misc/Measles.html](http://grantbrown.github.io/misc/Measles.html) to build my spatial SEIR model, however, an error happened:

> exception: Non-finite weights were generated
> error in value[[3L]] (cond): Aborting

My dataset and the codes is [here](https://github.com/Spatial-R/Dynamic-Model-for-Infectious-Disease/tree/master/SpatialSEIR). 

By the way, in your thesis, you don't recommend the user build the SEIRS model regarding to small proportation of recovery compartment in the whole population. However, for some infectious disease such as dengue, althought there is no cross-protection between different serotype,  the people who have infected this serotype will not be infected by the same serotype again . Therefore, in my opinion,  the S compartment from R is different from the origin S compartment (different risk to be infected).  Is there any way to fixed this problem? Or is there any example for the SEIRS model?

Another issue is that do you have compared with different definations to the spatial matrix in ABSEIR? If not, i will try this in my paper. Would you give me some suggestion on this?

**Comment by grantbrown** [comment]
There are a few things to try. 

First, make sure to grab the latest version of ABSEIR (1.2.1). Then, disable multivariate perturbation. Finally, you might want to increase both the batch-size, and the number of samples requested. 

As far as your question about SEIRS models, I see the point that you might want to introduce additional compartments. This is currently not implemented by ABSEIR, and given the wide range of possible compartment structures, this particular package isn't going to be a good vehicle for introducing that kind of arbitrary flexibility. 

You might want to check out Aaron King's POMP package for more general problems. I do plan to revisit this kind of development at some point, but can't speculate as to when I'll have a solution ready. 

Can you clarify what you mean with respect to different defintions of the spatial matrix? What kind of question are you trying to answer?

**Comment by grantbrown** [comment]
Closing as out of date
