### ISSUE TITLE
Analysis of Hand-foot-mouth disease using ABSEIR package

### ISSUE THREAD

**Issue by stevenhuyi** [grantbrown/ABSEIR#6]
Hi guys,

I'm now using the ABSEIR model to deal with the Hand-foot-mouth disease (HFMD) data in one province of Northwest China at county level, but encounter some problems. My HFMD data were aggregated by week in each county  from 2009 to 2016, and annual population and annual birth population data were also included.  As infected individuals are most under five years old, so the newly born enter the infectious process resulting in a unclosed transmission system. I would like to ask whether the current  ABSEIR model can consider the born population as well as annual variation of population in modeling diseases transmission. Thank you very much.

Yi

**Comment by grantbrown** [comment]
Hi Yi, unfortunately this is not currently supported.

**Comment by stevenhuyi** [comment]
Thanks for your reply, Grant. I get around with this new born issue and use the ABSEIR model to fit my HFMD data. But it is difficult for me to understand the results. the results are shown as follows:
[figure1.pdf](https://github.com/grantbrown/ABSEIR/files/2172548/figure1.pdf)
[figure2.pdf](https://github.com/grantbrown/ABSEIR/files/2172549/figure2.pdf)
figure 1 is the fitted curve to observed data and figure 2 is the corresponding EA-RN.
I am wondering why , in most counties, the EA-RN is always smaller than 1 yet HFMD still occur annually there. I can understand this would happen in county with small population as the annual cases might be imported ones, but I cannot imagine this occur in a large county, for example the first four counties in our analysis. Grant, would you please give some comments on this? Thanks.

Yi
